site_name: Pygent
site_url: https://marianochaves.github.io/pygent/
repo_url: https://github.com/marianochaves/pygent
theme: readthedocs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - Examples: examples.md
  - Custom Models: custom-models.md
  - API Reference: api-reference.md
plugins:
  - search
