site_name: Pygent
site_url: https://example.com/
repo_url: https://github.com/marianochaves/pygent
theme: readthedocs
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Configuration: configuration.md
  - API Reference: api-reference.md
plugins:
  - search
