site_name: Pygent
site_url: https://marianochaves.github.io/
repo_url: https://github.com/marianochaves/pygent
nav:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Command Line Interface (CLI): cli.md
  - Configuration: configuration.md
  - Tools: tools.md
  - Custom Models: custom-models.md
  - Architecture: architecture.md
  - Examples: examples.md
  - API Reference: api-reference.md
theme:
  name: material
  language: en
  logo: file_00000000b9e861f88eb06edc1f30e443.png
  favicon: file_00000000b9e861f88eb06edc1f30e443.png
  palette:
    - scheme: slate
      primary: black
      accent: '#1AFFA3'
  font: false
  features:
    - navigation.instant
    - content.code.copy
extra_css:
  - extra.css
extra_javascript:
  - extra.js
markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.]  # Look for modules in the current directory
          options:
            show_root_heading: True
            # show_source: True  # Disabled for now to address long lines
            members_order: source
            show_bases: True
            show_signature_annotations: True
            # separate_signature: True # Disabled for now, might contribute to line length issues
            docstring_section_style: spacy
            merge_init_into_class: True
            show_if_no_docstring: True
            # Options to potentially help with long lines and improve readability
            line_length: 80 # Attempt to wrap lines
            show_symbol_type_toc: True # Add symbol types to ToC for better navigation
            annotations_path: brief # Use brief paths for annotations
