site_name: Pygent
site_url: https://marianochaves.github.io/pygent/
repo_url: https://github.com/marianochaves/pygent
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: '(prefers-color-scheme: dark)'
  features:
    - content.code.copy
    - navigation.instant
nav:
  - 'Overview': index.md
  - 'Getting Started': getting-started.md
  - 'Command Line Interface (CLI)': cli.md
  - 'Configuration': configuration.md
  - 'Tools': tools.md
  - 'Custom Models': custom-models.md
  - 'Architecture': architecture.md
  - 'Examples': examples.md
  - 'API Reference': api-reference.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [pygent]