site_name: Pygent
site_url: https://marianochaves.github.io/pygent/
repo_url: https://github.com/marianochaves/pygent
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: '(prefers-color-scheme: dark)'
  features:
    - content.code.copy
    - navigation.instant
nav:
  - 'Visão Geral': index.md
  - 'Guia de Início Rápido': getting-started.md
  - 'Interface de Linha de Comando (CLI)': cli.md
  - 'Configuração': configuration.md
  - 'Ferramentas (Tools)': tools.md
  - 'Modelos Customizados': custom-models.md
  - 'Arquitetura': architecture.md
  - 'Exemplos': examples.md
  - 'Referência da API': api-reference.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [pygent]