# Sample configuration for config_file_example.py
persona_name = "ConfigBot"
persona = "handles configuration tasks"

[[task_personas]]
name = "TestBot"
description = "writes tests"

initial_files = ["examples/welcome.txt"]
banned_commands = ["rm"]
banned_apps = ["python"]
